C_LIB_BUILTINS = {
	"stdio.h": (
		("printf", "fp:0:"),
		("fprintf",  "fp:1:"),
		("snprintf", "fp:2:"),
		("sprintf",  "fp:1:"),
		("vprintf",  "fP:0:"),
		("vfprintf",  "fP:1:"),
		("vsnprintf", "fP:2:"),
		("vsprintf",  "fP:1:"),
		("scanf",  "fs:0:"),
		("fscanf", "fs:1:"),
		("sscanf", "fs:1:"),
		("vscanf", "fS:0:"),
		("vfscanf", "fS:1:"),
		("vsscanf", "fS:1:"),
		("fopen", "f"),
		("fread", "f"),
		("fwrite", "f"),
	),
	"wchar.h": (
		("wcschr", "f"),
		("wcscmp", "f"),
		("wcslen", "f"),
		("wcsncmp", "f"),
		("wmemchr", "f"),
		("wmemcmp", "f"),
		("wmemcpy", "f"),
		("wmemmove", "f"),
	),
	"ctype.h": (
		("isalnum", "fnU"),
		("isalpha", "fnU"),
		("isblank", "fnU"),
		("iscntrl", "fnU"),
		("isdigit", "fnU"),
		("isgraph", "fnU"),
		("islower", "fnU"),
		("isprint", "fnU"),
		("ispunct", "fnU"),
		("isspace", "fnU"),
		("isupper", "fnU"),
		("isxdigit", "fnU"),
		("tolower", "fnU"),
		("toupper", "fnU"),
	),
	"stdlib.h": (
		("abort", "fr"),
		("calloc", "f"),
		("exit", "fr"),
		("_Exit", "fr"),
		("malloc", "f"),
		("realloc", "f"),
		("free", "f"),
		("strtod", "f"),
		("strtof", "f"),
		("strtold", "f"),
		("strtol", "f"),
		("strtoll", "f"),
		("strtoul", "f"),
		("strtoull",  "f"),
		("aligned_alloc", "f"),
		("alloca", "f"),
		("abs", "fnc"),
		("labs", "fnc"),
		("llabs", "fnc"),
	),
	"strings.h": (
		("index",  "f"),
		("rindex",  "f"),
		("bzero",  "f"),
		("bcmp", "f"),
		("strcasecmp", "f"),
		("strncasecmp", "f"),
	),
	"string.h": (
		("memcpy", "f"),
		("memcmp", "f"),
		("memmove", "f"),
		("strcpy", "f"),
		("strncpy", "f"),
		("strcmp", "f"),
		("strncmp", "f"),
		("strcat", "f"),
		("strncat", "f"),
		("strxfrm", "f"),
		("memchr", "f"),
		("strchr", "f"),
		("strcspn", "f"),
		("strpbrk", "f"),
		("strrchr", "f"),
		("strspn", "f"),
		("strstr", "f"),
		("strtok", "f"),
		("memset", "f"),
		("strerror", "f"),
		("strlen", "f"),
		("memccpy", "f"),
		("mempcpy", "f"),
		("stpcpy", "f"),
		("stpncpy", "f"),
		("strdup",  "f"),
		("strndup", "f"),
		("strlcpy", "f"),
		("strlcat", "f"),
	),
	"malloc.h": (
		("memalign", "f"),
	),
	"setjmp.h": (
		("setjmp", "fjT"),
		("longjmp", "frT"),
		("_setjmp", "fjT"),
		("__sigsetjmp", "fjT"),
		("sigsetjmp", "fjT"),
		("savectx", "fjT"),
		("getcontext", "fjT"),
		("_longjmp", "frT"),
		("siglongjmp", "frT"),
	),
	"math.h": (
		("atan2", "fne"),
		("atan2f", "fne"),
		("atan2l", "fne"),
		("copysign", "fnc"),
		("copysignf", "fnc"),
		("copysignl", "fnc"),
		("fabs", "fnc"),
		("fabsf", "fnc"),
		("fabsl", "fnc"),
		("finite", "fnc"),
		("finitef", "fnc"),
		("finitel", "fnc"),
		("__finite", "fnc"),
		("__finitef", "fnc"),
		("__finitel", "fnc"),
		("fmod", "fne"),
		("fmodf", "fne"),
		("fmodl", "fne"),
		("frexp", "fn"),
		("frexpf", "fn"),
		("frexpl", "fn"),
		("ldexp", "fne"),
		("ldexpf", "fne"),
		("ldexpl", "fne"),
		("modf", "fn"),
		("modff", "fn"),
		("modfl", "fn"),
		("nan", "fUn"),
		("nanf", "fUn"),
		("nanl", "fUn"),
		("pow", "fne"),
		("powf", "fne"),
		("powl", "fne"),
		("acos", "fne"),
		("acosf", "fne"),
		("acosl", "fne"),
		("acosh", "fne"),
		("acoshf", "fne"),
		("acoshl", "fne"),
		("asin", "fne"),
		("asinf", "fne"),
		("asinl", "fne"),
		("asinh", "fne"),
		("asinhf", "fne"),
		("asinhl", "fne"),
		("atan", "fne"),
		("atanf", "fne"),
		("atanl", "fne"),
		("atanh", "fne"),
		("atanhf", "fne"),
		("atanhl", "fne"),
		("cbrt", "fnc"),
		("cbrtf", "fnc"),
		("cbrtl", "fnc"),
		("ceil", "fnc"),
		("ceilf", "fnc"),
		("ceill", "fnc"),
		("cos", "fne"),
		("cosf", "fne"),
		("cosl", "fne"),
		("cosh", "fne"),
		("coshf", "fne"),
		("coshl", "fne"),
		("erf", "fne"),
		("erff", "fne"),
		("erfl", "fne"),
		("erfc", "fne"),
		("erfcf", "fne"),
		("erfcl", "fne"),
		("exp", "fne"),
		("expf", "fne"),
		("expl", "fne"),
		("exp2", "fne"),
		("exp2f", "fne"),
		("exp2l", "fne"),
		("expm1", "fne"),
		("expm1f", "fne"),
		("expm1l", "fne"),
		("fdim", "fne"),
		("fdimf", "fne"),
		("fdiml", "fne"),
		("floor", "fnc"),
		("floorf", "fnc"),
		("floorl", "fnc"),
		("fma", "fne"),
		("fmaf", "fne"),
		("fmal", "fne"),
		("fmax", "fnc"),
		("fmaxf", "fnc"),
		("fmaxl", "fnc"),
		("fmin", "fnc"),
		("fminf", "fnc"),
		("fminl", "fnc"),
		("hypot", "fne"),
		("hypotf", "fne"),
		("hypotl", "fne"),
		("ilogb", "fne"),
		("ilogbf", "fne"),
		("ilogbl", "fne"),
		("lgamma", "fn"),
		("lgammaf", "fn"),
		("lgammal", "fn"),
		("llrint", "fne"),
		("llrintf", "fne"),
		("llrintl", "fne"),
		("llround", "fne"),
		("llroundf", "fne"),
		("llroundl", "fne"),
		("log", "fne"),
		("logf", "fne"),
		("logl", "fne"),
		("log10", "fne"),
		("log10f", "fne"),
		("log10l", "fne"),
		("log1p", "fne"),
		("log1pf", "fne"),
		("log1pl", "fne"),
		("log2", "fne"),
		("log2f", "fne"),
		("log2l", "fne"),
		("logb", "fne"),
		("logbf", "fne"),
		("logbl", "fne"),
		("lrint", "fne"),
		("lrintf", "fne"),
		("lrintl", "fne"),
		("lround", "fne"),
		("lroundf", "fne"),
		("lroundl", "fne"),
		("nearbyint", "fnc"),
		("nearbyintf", "fnc"),
		("nearbyintl", "fnc"),
		("nextafter", "fne"),
		("nextafterf", "fne"),
		("nextafterl", "fne"),
		("nexttoward", "fne"),
		("nexttowardf", "fne"),
		("nexttowardl", "fne"),
		("remainder", "fne"),
		("remainderf", "fne"),
		("remainderl", "fne"),
		("remquo", "fn"),
		("remquof", "fn"),
		("remquol", "fn"),
		("rint", "fnc"),
		("rintf", "fnc"),
		("rintl", "fnc"),
		("round", "fnc"),
		("roundf", "fnc"),
		("roundl", "fnc"),
		("scalbln", "fne"),
		("scalblnf", "fne"),
		("scalblnl", "fne"),
		("scalbn", "fne"),
		("scalbnf", "fne"),
		("scalbnl", "fne"),
		("sin", "fne"),
		("sinf", "fne"),
		("__sinpi", "fne"),
		("__sinpif", "fne"),
		("__cospi", "fne"),
		("__cospif", "fne"),
		("__tanpi", "fne"),
		("__tanpif", "fne"),
		("__exp10", "fne"),
		("__exp10f", "fne"),
		("sinl", "fne"),
		("sinh", "fne"),
		("sinhf", "fne"),
		("sinhl", "fne"),
		("sqrt", "fne"),
		("sqrtf", "fne"),
		("sqrtl", "fne"),
		("tan", "fne"),
		("tanf", "fne"),
		("tanl", "fne"),
		("tanh", "fne"),
		("tanhf", "fne"),
		("tanhl", "fne"),
		("tgamma", "fne"),
		("tgammaf", "fne"),
		("tgammal", "fne"),
		("trunc", "fnc"),
		("truncf", "fnc"),
		("truncl", "fnc"),
	),
	"stdarg.h": (
		("va_start", "fn"),
		("va_end", "fn"),
		("va_copy", "fn"),
	),
	"unistd.h": (
		("_exit", "fr"),
		("vfork", "fjT"),
	),
	"complex.h": (
		("cabs", "fne"),
		("cabsf", "fne"),
		("cabsl", "fne"),
		("cacos", "fne"),
		("cacosf", "fne"),
		("cacosl", "fne"),
		("cacosh", "fne"),
		("cacoshf", "fne"),
		("cacoshl", "fne"),
		("carg", "fne"),
		("cargf", "fne"),
		("cargl", "fne"),
		("casin", "fne"),
		("casinf", "fne"),
		("casinl", "fne"),
		("casinh", "fne"),
		("casinhf", "fne"),
		("casinhl", "fne"),
		("catan", "fne"),
		("catanf", "fne"),
		("catanl", "fne"),
		("catanh", "fne"),
		("catanhf", "fne"),
		("catanhl", "fne"),
		("ccos", "fne"),
		("ccosf", "fne"),
		("ccosl", "fne"),
		("ccosh", "fne"),
		("ccoshf", "fne"),
		("ccoshl", "fne"),
		("cexp", "fne"),
		("cexpf", "fne"),
		("cexpl", "fne"),
		("cimag", "fnc"),
		("cimagf", "fnc"),
		("cimagl", "fnc"),
		("conj", "fnc"),
		("conjf", "fnc"),
		("conjl", "fnc"),
		("clog", "fne"),
		("clogf", "fne"),
		("clogl", "fne"),
		("cproj", "fnc"),
		("cprojf", "fnc"),
		("cprojl", "fnc"),
		("cpow", "fne"),
		("cpowf", "fne"),
		("cpowl", "fne"),
		("creal", "fnc"),
		("crealf", "fnc"),
		("creall", "fnc"),
		("csin", "fne"),
		("csinf", "fne"),
		("csinl", "fne"),
		("csinh", "fne"),
		("csinhf", "fne"),
		("csinhl", "fne"),
		("csqrt", "fne"),
		("csqrtf", "fne"),
		("csqrtl", "fne"),
		("ctan", "fne"),
		("ctanf", "fne"),
		("ctanl", "fne"),
		("ctanh", "fne"),
		("ctanhf", "fne"),
		("ctanhl", "fne"),
	),
	"Blocks.h": (
		("_Block_object_assign", "f"),
		("_Block_object_dispose", "f"),
	)
}
COMPILER_BUILTINS = (
    ("__builtin_atan2", "ddd", "Fne"),
    ("__builtin_atan2f", "fff", "Fne"),
    ("__builtin_atan2l", "LdLdLd", "Fne"),
    ("__builtin_atan2f128", "LLdLLdLLd", "Fne"),
    ("__builtin_abs", "ii", "ncF"),
    ("__builtin_copysign", "ddd", "ncF"),
    ("__builtin_copysignf", "fff", "ncF"),
    ("__builtin_copysignf16", "hhh", "ncF"),
    ("__builtin_copysignl", "LdLdLd", "ncF"),
    ("__builtin_copysignf128", "LLdLLdLLd", "ncF"),
    ("__builtin_fabs", "dd", "ncF"),
    ("__builtin_fabsf", "ff", "ncF"),
    ("__builtin_fabsl", "LdLd", "ncF"),
    ("__builtin_fabsf16", "hh", "ncF"),
    ("__builtin_fabsf128", "LLdLLd", "ncF"),
    ("__builtin_fmod", "ddd", "Fne"),
    ("__builtin_fmodf", "fff", "Fne"),
    ("__builtin_fmodf16", "hhh", "Fne"),
    ("__builtin_fmodl", "LdLdLd", "Fne"),
    ("__builtin_fmodf128", "LLdLLdLLd", "Fne"),
    ("__builtin_frexp", "ddi*", "Fn"),
    ("__builtin_frexpf", "ffi*", "Fn"),
    ("__builtin_frexpl", "LdLdi*", "Fn"),
    ("__builtin_frexpf128", "LLdLLdi*", "Fn"),
    ("__builtin_huge_val", "d", "nc"),
    ("__builtin_huge_valf", "f", "nc"),
    ("__builtin_huge_vall", "Ld", "nc"),
    ("__builtin_huge_valf128", "LLd", "nc"),
    ("__builtin_inf", "d", "nc"),
    ("__builtin_inff", "f", "nc"),
    ("__builtin_infl", "Ld", "nc"),
    ("__builtin_inff128", "LLd", "nc"),
    ("__builtin_labs", "LiLi", "Fnc"),
    ("__builtin_llabs", "LLiLLi", "Fnc"),
    ("__builtin_ldexp", "ddi", "Fne"),
    ("__builtin_ldexpf", "ffi", "Fne"),
    ("__builtin_ldexpl", "LdLdi", "Fne"),
    ("__builtin_ldexpf128", "LLdLLdi", "Fne"),
    ("__builtin_modf", "ddd*", "Fn"),
    ("__builtin_modff", "fff*", "Fn"),
    ("__builtin_modfl", "LdLdLd*", "Fn"),
    ("__builtin_modff128", "LLdLLdLLd*", "Fn"),
    ("__builtin_nan", "dcC*", "FnU"),
    ("__builtin_nanf", "fcC*", "FnU"),
    ("__builtin_nanl", "LdcC*", "FnU"),
    ("__builtin_nanf128", "LLdcC*", "FnU"),
    ("__builtin_nans", "dcC*", "FnU"),
    ("__builtin_nansf", "fcC*", "FnU"),
    ("__builtin_nansl", "LdcC*", "FnU"),
    ("__builtin_nansf128", "LLdcC*", "FnU"),
    ("__builtin_powi", "ddi", "Fnc"),
    ("__builtin_powif", "ffi", "Fnc"),
    ("__builtin_powil", "LdLdi", "Fnc"),
    ("__builtin_pow", "ddd", "Fne"),
    ("__builtin_powf", "fff", "Fne"),
    ("__builtin_powf16", "hhh", "Fne"),
    ("__builtin_powl", "LdLdLd", "Fne"),
    ("__builtin_powf128", "LLdLLdLLd", "Fne"),
    ("__builtin_acos", "dd", "Fne"),
    ("__builtin_acosf", "ff", "Fne"),
    ("__builtin_acosl", "LdLd", "Fne"),
    ("__builtin_acosf128", "LLdLLd", "Fne"),
    ("__builtin_acosh", "dd", "Fne"),
    ("__builtin_acoshf", "ff", "Fne"),
    ("__builtin_acoshl", "LdLd", "Fne"),
    ("__builtin_acoshf128", "LLdLLd", "Fne"),
    ("__builtin_asin", "dd", "Fne"),
    ("__builtin_asinf", "ff", "Fne"),
    ("__builtin_asinl", "LdLd", "Fne"),
    ("__builtin_asinf128", "LLdLLd", "Fne"),
    ("__builtin_asinh", "dd", "Fne"),
    ("__builtin_asinhf", "ff", "Fne"),
    ("__builtin_asinhl", "LdLd", "Fne"),
    ("__builtin_asinhf128", "LLdLLd", "Fne"),
    ("__builtin_atan", "dd", "Fne"),
    ("__builtin_atanf", "ff", "Fne"),
    ("__builtin_atanl", "LdLd", "Fne"),
    ("__builtin_atanf128", "LLdLLd", "Fne"),
    ("__builtin_atanh", "dd", "Fne"),
    ("__builtin_atanhf", "ff", "Fne"),
    ("__builtin_atanhl", "LdLd", "Fne"),
    ("__builtin_atanhf128", "LLdLLd", "Fne"),
    ("__builtin_cbrt", "dd", "Fnc"),
    ("__builtin_cbrtf", "ff", "Fnc"),
    ("__builtin_cbrtl", "LdLd", "Fnc"),
    ("__builtin_cbrtf128", "LLdLLd", "Fnc"),
    ("__builtin_ceil", "dd", "Fnc"),
    ("__builtin_ceilf", "ff", "Fnc"),
    ("__builtin_ceilf16", "hh", "Fnc"),
    ("__builtin_ceill", "LdLd", "Fnc"),
    ("__builtin_ceilf128", "LLdLLd", "Fnc"),
    ("__builtin_cos", "dd", "Fne"),
    ("__builtin_cosf", "ff", "Fne"),
    ("__builtin_cosf16", "hh", "Fne"),
    ("__builtin_cosh", "dd", "Fne"),
    ("__builtin_coshf", "ff", "Fne"),
    ("__builtin_coshl", "LdLd", "Fne"),
    ("__builtin_coshf128", "LLdLLd", "Fne"),
    ("__builtin_cosl", "LdLd", "Fne"),
    ("__builtin_cosf128", "LLdLLd", "Fne"),
    ("__builtin_erf", "dd", "Fne"),
    ("__builtin_erff", "ff", "Fne"),
    ("__builtin_erfl", "LdLd", "Fne"),
    ("__builtin_erff128", "LLdLLd", "Fne"),
    ("__builtin_erfc", "dd", "Fne"),
    ("__builtin_erfcf", "ff", "Fne"),
    ("__builtin_erfcl", "LdLd", "Fne"),
    ("__builtin_erfcf128", "LLdLLd", "Fne"),
    ("__builtin_exp", "dd", "Fne"),
    ("__builtin_expf", "ff", "Fne"),
    ("__builtin_expf16", "hh", "Fne"),
    ("__builtin_expl", "LdLd", "Fne"),
    ("__builtin_expf128", "LLdLLd", "Fne"),
    ("__builtin_exp2", "dd", "Fne"),
    ("__builtin_exp2f", "ff", "Fne"),
    ("__builtin_exp2f16", "hh", "Fne"),
    ("__builtin_exp2l", "LdLd", "Fne"),
    ("__builtin_exp2f128", "LLdLLd", "Fne"),
    ("__builtin_expm1", "dd", "Fne"),
    ("__builtin_expm1f", "ff", "Fne"),
    ("__builtin_expm1l", "LdLd", "Fne"),
    ("__builtin_expm1f128", "LLdLLd", "Fne"),
    ("__builtin_fdim", "ddd", "Fne"),
    ("__builtin_fdimf", "fff", "Fne"),
    ("__builtin_fdiml", "LdLdLd", "Fne"),
    ("__builtin_fdimf128", "LLdLLdLLd", "Fne"),
    ("__builtin_floor", "dd", "Fnc"),
    ("__builtin_floorf", "ff", "Fnc"),
    ("__builtin_floorf16", "hh", "Fnc"),
    ("__builtin_floorl", "LdLd", "Fnc"),
    ("__builtin_floorf128", "LLdLLd", "Fnc"),
    ("__builtin_fma", "dddd", "Fne"),
    ("__builtin_fmaf", "ffff", "Fne"),
    ("__builtin_fmaf16", "hhhh", "Fne"),
    ("__builtin_fmal", "LdLdLdLd", "Fne"),
    ("__builtin_fmaf128", "LLdLLdLLdLLd", "Fne"),
    ("__builtin_fmax", "ddd", "Fnc"),
    ("__builtin_fmaxf", "fff", "Fnc"),
    ("__builtin_fmaxf16", "hhh", "Fnc"),
    ("__builtin_fmaxl", "LdLdLd", "Fnc"),
    ("__builtin_fmaxf128", "LLdLLdLLd", "Fnc"),
    ("__builtin_fmin", "ddd", "Fnc"),
    ("__builtin_fminf", "fff", "Fnc"),
    ("__builtin_fminf16", "hhh", "Fnc"),
    ("__builtin_fminl", "LdLdLd", "Fnc"),
    ("__builtin_fminf128", "LLdLLdLLd", "Fnc"),
    ("__builtin_hypot", "ddd", "Fne"),
    ("__builtin_hypotf", "fff", "Fne"),
    ("__builtin_hypotl", "LdLdLd", "Fne"),
    ("__builtin_hypotf128", "LLdLLdLLd", "Fne"),
    ("__builtin_ilogb", "id", "Fne"),
    ("__builtin_ilogbf", "if", "Fne"),
    ("__builtin_ilogbl", "iLd", "Fne"),
    ("__builtin_ilogbf128", "iLLd", "Fne"),
    ("__builtin_lgamma", "dd", "Fn"),
    ("__builtin_lgammaf", "ff", "Fn"),
    ("__builtin_lgammal", "LdLd", "Fn"),
    ("__builtin_lgammaf128", "LLdLLd", "Fn"),
    ("__builtin_llrint", "LLid", "Fne"),
    ("__builtin_llrintf", "LLif", "Fne"),
    ("__builtin_llrintl", "LLiLd", "Fne"),
    ("__builtin_llrintf128", "LLiLLd", "Fne"),
    ("__builtin_llround", "LLid", "Fne"),
    ("__builtin_llroundf", "LLif", "Fne"),
    ("__builtin_llroundl", "LLiLd", "Fne"),
    ("__builtin_llroundf128", "LLiLLd", "Fne"),
    ("__builtin_log", "dd", "Fne"),
    ("__builtin_log10", "dd", "Fne"),
    ("__builtin_log10f", "ff", "Fne"),
    ("__builtin_log10f16", "hh", "Fne"),
    ("__builtin_log10l", "LdLd", "Fne"),
    ("__builtin_log10f128", "LLdLLd", "Fne"),
    ("__builtin_log1p", "dd", "Fne"),
    ("__builtin_log1pf", "ff", "Fne"),
    ("__builtin_log1pl", "LdLd", "Fne"),
    ("__builtin_log1pf128", "LLdLLd", "Fne"),
    ("__builtin_log2", "dd", "Fne"),
    ("__builtin_log2f", "ff", "Fne"),
    ("__builtin_log2f16", "hh", "Fne"),
    ("__builtin_log2l", "LdLd", "Fne"),
    ("__builtin_log2f128", "LLdLLd", "Fne"),
    ("__builtin_logb", "dd", "Fne"),
    ("__builtin_logbf", "ff", "Fne"),
    ("__builtin_logbl", "LdLd", "Fne"),
    ("__builtin_logbf128", "LLdLLd", "Fne"),
    ("__builtin_logf", "ff", "Fne"),
    ("__builtin_logf16", "hh", "Fne"),
    ("__builtin_logl", "LdLd", "Fne"),
    ("__builtin_logf128", "LLdLLd", "Fne"),
    ("__builtin_lrint", "Lid", "Fne"),
    ("__builtin_lrintf", "Lif", "Fne"),
    ("__builtin_lrintl", "LiLd", "Fne"),
    ("__builtin_lrintf128", "LiLLd", "Fne"),
    ("__builtin_lround", "Lid", "Fne"),
    ("__builtin_lroundf", "Lif", "Fne"),
    ("__builtin_lroundl", "LiLd", "Fne"),
    ("__builtin_lroundf128", "LiLLd", "Fne"),
    ("__builtin_nearbyint", "dd", "Fnc"),
    ("__builtin_nearbyintf", "ff", "Fnc"),
    ("__builtin_nearbyintl", "LdLd", "Fnc"),
    ("__builtin_nearbyintf128", "LLdLLd", "Fnc"),
    ("__builtin_nextafter", "ddd", "Fne"),
    ("__builtin_nextafterf", "fff", "Fne"),
    ("__builtin_nextafterl", "LdLdLd", "Fne"),
    ("__builtin_nextafterf128", "LLdLLdLLd", "Fne"),
    ("__builtin_nexttoward", "ddLd", "Fne"),
    ("__builtin_nexttowardf", "ffLd", "Fne"),
    ("__builtin_nexttowardl", "LdLdLd", "Fne"),
    ("__builtin_nexttowardf128", "LLdLLdLLd", "Fne"),
    ("__builtin_remainder", "ddd", "Fne"),
    ("__builtin_remainderf", "fff", "Fne"),
    ("__builtin_remainderl", "LdLdLd", "Fne"),
    ("__builtin_remainderf128", "LLdLLdLLd", "Fne"),
    ("__builtin_remquo", "dddi*", "Fn"),
    ("__builtin_remquof", "fffi*", "Fn"),
    ("__builtin_remquol", "LdLdLdi*", "Fn"),
    ("__builtin_remquof128", "LLdLLdLLdi*", "Fn"),
    ("__builtin_rint", "dd", "Fnc"),
    ("__builtin_rintf", "ff", "Fnc"),
    ("__builtin_rintf16", "hh", "Fnc"),
    ("__builtin_rintl", "LdLd", "Fnc"),
    ("__builtin_rintf128", "LLdLLd", "Fnc"),
    ("__builtin_round", "dd", "Fnc"),
    ("__builtin_roundf", "ff", "Fnc"),
    ("__builtin_roundf16", "hh", "Fnc"),
    ("__builtin_roundl", "LdLd", "Fnc"),
    ("__builtin_roundf128", "LLdLLd", "Fnc"),
    ("__builtin_scalbln", "ddLi", "Fne"),
    ("__builtin_scalblnf", "ffLi", "Fne"),
    ("__builtin_scalblnl", "LdLdLi", "Fne"),
    ("__builtin_scalblnf128", "LLdLLdLi", "Fne"),
    ("__builtin_scalbn", "ddi", "Fne"),
    ("__builtin_scalbnf", "ffi", "Fne"),
    ("__builtin_scalbnl", "LdLdi", "Fne"),
    ("__builtin_scalbnf128", "LLdLLdi", "Fne"),
    ("__builtin_sin", "dd", "Fne"),
    ("__builtin_sinf", "ff", "Fne"),
    ("__builtin_sinf16", "hh", "Fne"),
    ("__builtin_sinh", "dd", "Fne"),
    ("__builtin_sinhf", "ff", "Fne"),
    ("__builtin_sinhl", "LdLd", "Fne"),
    ("__builtin_sinhf128", "LLdLLd", "Fne"),
    ("__builtin_sinl", "LdLd", "Fne"),
    ("__builtin_sinf128", "LLdLLd", "Fne"),
    ("__builtin_sqrt", "dd", "Fne"),
    ("__builtin_sqrtf", "ff", "Fne"),
    ("__builtin_sqrtf16", "hh", "Fne"),
    ("__builtin_sqrtl", "LdLd", "Fne"),
    ("__builtin_sqrtf128", "LLdLLd", "Fne"),
    ("__builtin_tan", "dd", "Fne"),
    ("__builtin_tanf", "ff", "Fne"),
    ("__builtin_tanh", "dd", "Fne"),
    ("__builtin_tanhf", "ff", "Fne"),
    ("__builtin_tanhl", "LdLd", "Fne"),
    ("__builtin_tanhf128", "LLdLLd", "Fne"),
    ("__builtin_tanl", "LdLd", "Fne"),
    ("__builtin_tanf128", "LLdLLd", "Fne"),
    ("__builtin_tgamma", "dd", "Fne"),
    ("__builtin_tgammaf", "ff", "Fne"),
    ("__builtin_tgammal", "LdLd", "Fne"),
    ("__builtin_tgammaf128", "LLdLLd", "Fne"),
    ("__builtin_trunc", "dd", "Fnc"),
    ("__builtin_truncf", "ff", "Fnc"),
    ("__builtin_truncl", "LdLd", "Fnc"),
    ("__builtin_truncf128", "LLdLLd", "Fnc"),
    ("__builtin_truncf16", "hh", "Fnc"),
    ("__builtin_flt_rounds", "i", "n"),
    ("__builtin_cabs", "dXd", "Fne"),
    ("__builtin_cabsf", "fXf", "Fne"),
    ("__builtin_cabsl", "LdXLd", "Fne"),
    ("__builtin_cacos", "XdXd", "Fne"),
    ("__builtin_cacosf", "XfXf", "Fne"),
    ("__builtin_cacosh", "XdXd", "Fne"),
    ("__builtin_cacoshf", "XfXf", "Fne"),
    ("__builtin_cacoshl", "XLdXLd", "Fne"),
    ("__builtin_cacosl", "XLdXLd", "Fne"),
    ("__builtin_carg", "dXd", "Fne"),
    ("__builtin_cargf", "fXf", "Fne"),
    ("__builtin_cargl", "LdXLd", "Fne"),
    ("__builtin_casin", "XdXd", "Fne"),
    ("__builtin_casinf", "XfXf", "Fne"),
    ("__builtin_casinh", "XdXd", "Fne"),
    ("__builtin_casinhf", "XfXf", "Fne"),
    ("__builtin_casinhl", "XLdXLd", "Fne"),
    ("__builtin_casinl", "XLdXLd", "Fne"),
    ("__builtin_catan", "XdXd", "Fne"),
    ("__builtin_catanf", "XfXf", "Fne"),
    ("__builtin_catanh", "XdXd", "Fne"),
    ("__builtin_catanhf", "XfXf", "Fne"),
    ("__builtin_catanhl", "XLdXLd", "Fne"),
    ("__builtin_catanl", "XLdXLd", "Fne"),
    ("__builtin_ccos", "XdXd", "Fne"),
    ("__builtin_ccosf", "XfXf", "Fne"),
    ("__builtin_ccosl", "XLdXLd", "Fne"),
    ("__builtin_ccosh", "XdXd", "Fne"),
    ("__builtin_ccoshf", "XfXf", "Fne"),
    ("__builtin_ccoshl", "XLdXLd", "Fne"),
    ("__builtin_cexp", "XdXd", "Fne"),
    ("__builtin_cexpf", "XfXf", "Fne"),
    ("__builtin_cexpl", "XLdXLd", "Fne"),
    ("__builtin_cimag", "dXd", "Fnc"),
    ("__builtin_cimagf", "fXf", "Fnc"),
    ("__builtin_cimagl", "LdXLd", "Fnc"),
    ("__builtin_conj", "XdXd", "Fnc"),
    ("__builtin_conjf", "XfXf", "Fnc"),
    ("__builtin_conjl", "XLdXLd", "Fnc"),
    ("__builtin_clog", "XdXd", "Fne"),
    ("__builtin_clogf", "XfXf", "Fne"),
    ("__builtin_clogl", "XLdXLd", "Fne"),
    ("__builtin_cproj", "XdXd", "Fnc"),
    ("__builtin_cprojf", "XfXf", "Fnc"),
    ("__builtin_cprojl", "XLdXLd", "Fnc"),
    ("__builtin_cpow", "XdXdXd", "Fne"),
    ("__builtin_cpowf", "XfXfXf", "Fne"),
    ("__builtin_cpowl", "XLdXLdXLd", "Fne"),
    ("__builtin_creal", "dXd", "Fnc"),
    ("__builtin_crealf", "fXf", "Fnc"),
    ("__builtin_creall", "LdXLd", "Fnc"),
    ("__builtin_csin", "XdXd", "Fne"),
    ("__builtin_csinf", "XfXf", "Fne"),
    ("__builtin_csinl", "XLdXLd", "Fne"),
    ("__builtin_csinh", "XdXd", "Fne"),
    ("__builtin_csinhf", "XfXf", "Fne"),
    ("__builtin_csinhl", "XLdXLd", "Fne"),
    ("__builtin_csqrt", "XdXd", "Fne"),
    ("__builtin_csqrtf", "XfXf", "Fne"),
    ("__builtin_csqrtl", "XLdXLd", "Fne"),
    ("__builtin_ctan", "XdXd", "Fne"),
    ("__builtin_ctanf", "XfXf", "Fne"),
    ("__builtin_ctanl", "XLdXLd", "Fne"),
    ("__builtin_ctanh", "XdXd", "Fne"),
    ("__builtin_ctanhf", "XfXf", "Fne"),
    ("__builtin_ctanhl", "XLdXLd", "Fne"),
    ("__builtin_isgreater", "i.", "Fnct"),
    ("__builtin_isgreaterequal", "i.", "Fnct"),
    ("__builtin_isless", "i.", "Fnct"),
    ("__builtin_islessequal", "i.", "Fnct"),
    ("__builtin_islessgreater", "i.", "Fnct"),
    ("__builtin_isunordered", "i.", "Fnct"),
    ("__builtin_fpclassify", "iiiiii.", "Fnct"),
    ("__builtin_isfinite", "i.", "Fnct"),
    ("__builtin_isinf", "i.", "Fnct"),
    ("__builtin_isinf_sign", "i.", "Fnct"),
    ("__builtin_isnan", "i.", "Fnct"),
    ("__builtin_isnormal", "i.", "Fnct"),
    ("__builtin_signbit", "i.", "Fnct"),
    ("__builtin_signbitf", "if", "Fnc"),
    ("__builtin_signbitl", "iLd", "Fnc"),
    ("__builtin_canonicalize", "dd", "nc"),
    ("__builtin_canonicalizef", "ff", "nc"),
    ("__builtin_canonicalizef16", "hh", "nc"),
    ("__builtin_canonicalizel", "LdLd", "nc"),
    ("__builtin_clzs", "iUs", "nc"),
    ("__builtin_clz", "iUi", "nc"),
    ("__builtin_clzl", "iULi", "nc"),
    ("__builtin_clzll", "iULLi", "nc"),
    ("__builtin_ctzs", "iUs", "nc"),
    ("__builtin_ctz", "iUi", "nc"),
    ("__builtin_ctzl", "iULi", "nc"),
    ("__builtin_ctzll", "iULLi", "nc"),
    ("__builtin_ffs", "ii", "Fnc"),
    ("__builtin_ffsl", "iLi", "Fnc"),
    ("__builtin_ffsll", "iLLi", "Fnc"),
    ("__builtin_parity", "iUi", "nc"),
    ("__builtin_parityl", "iULi", "nc"),
    ("__builtin_parityll", "iULLi", "nc"),
    ("__builtin_popcount", "iUi", "nc"),
    ("__builtin_popcountl", "iULi", "nc"),
    ("__builtin_popcountll", "iULLi", "nc"),
    ("__builtin_clrsb", "ii", "nc"),
    ("__builtin_clrsbl", "iLi", "nc"),
    ("__builtin_clrsbll", "iLLi", "nc"),
    ("__builtin_bswap16", "UsUs", "nc"),
    ("__builtin_bswap32", "UZiUZi", "nc"),
    ("__builtin_bswap64", "UWiUWi", "nc"),
    ("__builtin_bitreverse8", "UcUc", "nc"),
    ("__builtin_bitreverse16", "UsUs", "nc"),
    ("__builtin_bitreverse32", "UZiUZi", "nc"),
    ("__builtin_bitreverse64", "UWiUWi", "nc"),
    ("__builtin_rotateleft8", "UcUcUc", "nc"),
    ("__builtin_rotateleft16", "UsUsUs", "nc"),
    ("__builtin_rotateleft32", "UZiUZiUZi", "nc"),
    ("__builtin_rotateleft64", "UWiUWiUWi", "nc"),
    ("__builtin_rotateright8", "UcUcUc", "nc"),
    ("__builtin_rotateright16", "UsUsUs", "nc"),
    ("__builtin_rotateright32", "UZiUZiUZi", "nc"),
    ("__builtin_rotateright64", "UWiUWiUWi", "nc"),
    ("__builtin_calloc", "v*zz", "nF"),
    ("__builtin_constant_p", "i.", "nctu"),
    ("__builtin_classify_type", "i.", "nctu"),
    ("__builtin___CFStringMakeConstantString", "FC*cC*", "nc"),
    ("__builtin___NSStringMakeConstantString", "FC*cC*", "nc"),
    ("__builtin_va_start", "vA.", "nt"),
    ("__builtin_va_end", "vA", "n"),
    ("__builtin_va_copy", "vAA", "n"),
    ("__builtin_stdarg_start", "vA.", "nt"),
    ("__builtin_assume_aligned", "v*vC*z.", "nc"),
    ("__builtin_bcmp", "ivC*vC*z", "Fn"),
    ("__builtin_bcopy", "vv*v*z", "n"),
    ("__builtin_bzero", "vv*z", "nF"),
    ("__builtin_fprintf", "iP*cC*.", "Fp:1:"),
    ("__builtin_free", "vv*", "nF"),
    ("__builtin_malloc", "v*z", "nF"),
    ("__builtin_memchr", "v*vC*iz", "nF"),
    ("__builtin_memcmp", "ivC*vC*z", "nF"),
    ("__builtin_memcpy", "v*v*vC*z", "nF"),
    ("__builtin_memcpy_inline", "vv*vC*Iz", "nt"),
    ("__builtin_memmove", "v*v*vC*z", "nF"),
    ("__builtin_mempcpy", "v*v*vC*z", "nF"),
    ("__builtin_memset", "v*v*iz", "nF"),
    ("__builtin_printf", "icC*.", "Fp:0:"),
    ("__builtin_stpcpy", "c*c*cC*", "nF"),
    ("__builtin_stpncpy", "c*c*cC*z", "nF"),
    ("__builtin_strcasecmp", "icC*cC*", "nF"),
    ("__builtin_strcat", "c*c*cC*", "nF"),
    ("__builtin_strchr", "c*cC*i", "nF"),
    ("__builtin_strcmp", "icC*cC*", "nF"),
    ("__builtin_strcpy", "c*c*cC*", "nF"),
    ("__builtin_strcspn", "zcC*cC*", "nF"),
    ("__builtin_strdup", "c*cC*", "nF"),
    ("__builtin_strlen", "zcC*", "nF"),
    ("__builtin_strncasecmp", "icC*cC*z", "nF"),
    ("__builtin_strncat", "c*c*cC*z", "nF"),
    ("__builtin_strncmp", "icC*cC*z", "nF"),
    ("__builtin_strncpy", "c*c*cC*z", "nF"),
    ("__builtin_strndup", "c*cC*z", "nF"),
    ("__builtin_strpbrk", "c*cC*cC*", "nF"),
    ("__builtin_strrchr", "c*cC*i", "nF"),
    ("__builtin_strspn", "zcC*cC*", "nF"),
    ("__builtin_strstr", "c*cC*cC*", "nF"),
    ("__builtin_wcschr", "w*wC*w", "nF"),
    ("__builtin_wcscmp", "iwC*wC*", "nF"),
    ("__builtin_wcslen", "zwC*", "nF"),
    ("__builtin_wcsncmp", "iwC*wC*z", "nF"),
    ("__builtin_wmemchr", "w*wC*wz", "nF"),
    ("__builtin_wmemcmp", "iwC*wC*z", "nF"),
    ("__builtin_wmemcpy", "w*w*wC*z", "nF"),
    ("__builtin_wmemmove", "w*w*wC*z", "nF"),
    ("__builtin_realloc", "v*v*z", "nF"),
    ("__builtin_return_address", "v*IUi", "n"),
    ("__builtin_extract_return_addr", "v*v*", "n"),
    ("__builtin_frame_address", "v*IUi", "n"),
    ("__builtin___clear_cache", "vc*c*", "n"),
    ("__builtin_setjmp", "iv**", "j"),
    ("__builtin_longjmp", "vv**i", "r"),
    ("__builtin_unwind_init", "v", ""),
    ("__builtin_eh_return_data_regno", "iIi", "nc"),
    ("__builtin_snprintf", "ic*zcC*.", "nFp:2:"),
    ("__builtin_sprintf", "ic*cC*.", "nFP:1:"),
    ("__builtin_vsnprintf", "ic*zcC*a", "nFP:2:"),
    ("__builtin_vsprintf", "ic*cC*a", "nFP:1:"),
    ("__builtin_thread_pointer", "v*", "nc"),
    ("__builtin_launder", "v*v*", "nt"),
    ("__builtin_eh_return", "vzv*", "r"),
    ("__builtin_frob_return_addr", "v*v*", "n"),
    ("__builtin_dwarf_cfa", "v*", "n"),
    ("__builtin_init_dwarf_reg_size_table", "vv*", "n"),
    ("__builtin_dwarf_sp_column", "Ui", "n"),
    ("__builtin_extend_pointer", "ULLiv*", "n"),
    ("__builtin_object_size", "zvC*i", "nu"),
    ("__builtin_dynamic_object_size", "zvC*i", "nu"),
    ("__builtin___memcpy_chk", "v*v*vC*zz", "nF"),
    ("__builtin___memccpy_chk", "v*v*vC*izz", "nF"),
    ("__builtin___memmove_chk", "v*v*vC*zz", "nF"),
    ("__builtin___mempcpy_chk", "v*v*vC*zz", "nF"),
    ("__builtin___memset_chk", "v*v*izz", "nF"),
    ("__builtin___stpcpy_chk", "c*c*cC*z", "nF"),
    ("__builtin___strcat_chk", "c*c*cC*z", "nF"),
    ("__builtin___strcpy_chk", "c*c*cC*z", "nF"),
    ("__builtin___strlcat_chk", "zc*cC*zz", "nF"),
    ("__builtin___strlcpy_chk", "zc*cC*zz", "nF"),
    ("__builtin___strncat_chk", "c*c*cC*zz", "nF"),
    ("__builtin___strncpy_chk", "c*c*cC*zz", "nF"),
    ("__builtin___stpncpy_chk", "c*c*cC*zz", "nF"),
    ("__builtin___snprintf_chk", "ic*zizcC*.", "Fp:4:"),
    ("__builtin___sprintf_chk", "ic*izcC*.", "Fp:3:"),
    ("__builtin___vsnprintf_chk", "ic*zizcC*a", "FP:4:"),
    ("__builtin___vsprintf_chk", "ic*izcC*a", "FP:3:"),
    ("__builtin___fprintf_chk", "iP*icC*.", "Fp:2:"),
    ("__builtin___printf_chk", "iicC*.", "Fp:1:"),
    ("__builtin___vfprintf_chk", "iP*icC*a", "FP:2:"),
    ("__builtin___vprintf_chk", "iicC*a", "FP:1:"),
    ("__builtin_unpredictable", "LiLi", "nc"),
    ("__builtin_expect", "LiLiLi", "nc"),
    ("__builtin_expect_with_probability", "LiLiLid", "nc"),
    ("__builtin_prefetch", "vvC*.", "nc"),
    ("__builtin_readcyclecounter", "ULLi", "n"),
    ("__builtin_trap", "v", "nr"),
    ("__builtin_debugtrap", "v", "n"),
    ("__builtin_unreachable", "v", "nr"),
    ("__builtin_shufflevector", "v.", "nct"),
    ("__builtin_convertvector", "v.", "nct"),
    ("__builtin_alloca", "v*z", "Fn"),
    ("__builtin_alloca_uninitialized", "v*z", "Fn"),
    ("__builtin_alloca_with_align", "v*zIz", "Fn"),
    ("__builtin_alloca_with_align_uninitialized", "v*zIz", "Fn"),
    ("__builtin_call_with_static_chain", "v.", "nt"),
    ("__builtin_elementwise_abs", "v.", "nct"),
    ("__builtin_elementwise_max", "v.", "nct"),
    ("__builtin_elementwise_min", "v.", "nct"),
    ("__builtin_elementwise_ceil", "v.", "nct"),
    ("__builtin_elementwise_floor", "v.", "nct"),
    ("__builtin_elementwise_roundeven", "v.", "nct"),
    ("__builtin_elementwise_trunc", "v.", "nct"),
    ("__builtin_reduce_max", "v.", "nct"),
    ("__builtin_reduce_min", "v.", "nct"),
    ("__builtin_reduce_xor", "v.", "nct"),
    ("__builtin_reduce_or", "v.", "nct"),
    ("__builtin_reduce_and", "v.", "nct"),
    ("__builtin_matrix_transpose", "v.", "nFt"),
    ("__builtin_matrix_column_major_load", "v.", "nFt"),
    ("__builtin_matrix_column_major_store", "v.", "nFt"),
    ("__sync_fetch_and_add", "v.", "t"),
    ("__sync_fetch_and_add_1", "ccD*c.", "nt"),
    ("__sync_fetch_and_add_2", "ssD*s.", "nt"),
    ("__sync_fetch_and_add_4", "iiD*i.", "nt"),
    ("__sync_fetch_and_add_8", "LLiLLiD*LLi.", "nt"),
    ("__sync_fetch_and_add_16", "LLLiLLLiD*LLLi.", "nt"),
    ("__sync_fetch_and_sub", "v.", "t"),
    ("__sync_fetch_and_sub_1", "ccD*c.", "nt"),
    ("__sync_fetch_and_sub_2", "ssD*s.", "nt"),
    ("__sync_fetch_and_sub_4", "iiD*i.", "nt"),
    ("__sync_fetch_and_sub_8", "LLiLLiD*LLi.", "nt"),
    ("__sync_fetch_and_sub_16", "LLLiLLLiD*LLLi.", "nt"),
    ("__sync_fetch_and_or", "v.", "t"),
    ("__sync_fetch_and_or_1", "ccD*c.", "nt"),
    ("__sync_fetch_and_or_2", "ssD*s.", "nt"),
    ("__sync_fetch_and_or_4", "iiD*i.", "nt"),
    ("__sync_fetch_and_or_8", "LLiLLiD*LLi.", "nt"),
    ("__sync_fetch_and_or_16", "LLLiLLLiD*LLLi.", "nt"),
    ("__sync_fetch_and_and", "v.", "t"),
    ("__sync_fetch_and_and_1", "ccD*c.", "tn"),
    ("__sync_fetch_and_and_2", "ssD*s.", "tn"),
    ("__sync_fetch_and_and_4", "iiD*i.", "tn"),
    ("__sync_fetch_and_and_8", "LLiLLiD*LLi.", "tn"),
    ("__sync_fetch_and_and_16", "LLLiLLLiD*LLLi.", "tn"),
    ("__sync_fetch_and_xor", "v.", "t"),
    ("__sync_fetch_and_xor_1", "ccD*c.", "tn"),
    ("__sync_fetch_and_xor_2", "ssD*s.", "tn"),
    ("__sync_fetch_and_xor_4", "iiD*i.", "tn"),
    ("__sync_fetch_and_xor_8", "LLiLLiD*LLi.", "tn"),
    ("__sync_fetch_and_xor_16", "LLLiLLLiD*LLLi.", "tn"),
    ("__sync_fetch_and_nand", "v.", "t"),
    ("__sync_fetch_and_nand_1", "ccD*c.", "tn"),
    ("__sync_fetch_and_nand_2", "ssD*s.", "tn"),
    ("__sync_fetch_and_nand_4", "iiD*i.", "tn"),
    ("__sync_fetch_and_nand_8", "LLiLLiD*LLi.", "tn"),
    ("__sync_fetch_and_nand_16", "LLLiLLLiD*LLLi.", "tn"),
    ("__sync_add_and_fetch", "v.", "t"),
    ("__sync_add_and_fetch_1", "ccD*c.", "tn"),
    ("__sync_add_and_fetch_2", "ssD*s.", "tn"),
    ("__sync_add_and_fetch_4", "iiD*i.", "tn"),
    ("__sync_add_and_fetch_8", "LLiLLiD*LLi.", "tn"),
    ("__sync_add_and_fetch_16", "LLLiLLLiD*LLLi.", "tn"),
    ("__sync_sub_and_fetch", "v.", "t"),
    ("__sync_sub_and_fetch_1", "ccD*c.", "tn"),
    ("__sync_sub_and_fetch_2", "ssD*s.", "tn"),
    ("__sync_sub_and_fetch_4", "iiD*i.", "tn"),
    ("__sync_sub_and_fetch_8", "LLiLLiD*LLi.", "tn"),
    ("__sync_sub_and_fetch_16", "LLLiLLLiD*LLLi.", "tn"),
    ("__sync_or_and_fetch", "v.", "t"),
    ("__sync_or_and_fetch_1", "ccD*c.", "tn"),
    ("__sync_or_and_fetch_2", "ssD*s.", "tn"),
    ("__sync_or_and_fetch_4", "iiD*i.", "tn"),
    ("__sync_or_and_fetch_8", "LLiLLiD*LLi.", "tn"),
    ("__sync_or_and_fetch_16", "LLLiLLLiD*LLLi.", "tn"),
    ("__sync_and_and_fetch", "v.", "t"),
    ("__sync_and_and_fetch_1", "ccD*c.", "tn"),
    ("__sync_and_and_fetch_2", "ssD*s.", "tn"),
    ("__sync_and_and_fetch_4", "iiD*i.", "tn"),
    ("__sync_and_and_fetch_8", "LLiLLiD*LLi.", "tn"),
    ("__sync_and_and_fetch_16", "LLLiLLLiD*LLLi.", "tn"),
    ("__sync_xor_and_fetch", "v.", "t"),
    ("__sync_xor_and_fetch_1", "ccD*c.", "tn"),
    ("__sync_xor_and_fetch_2", "ssD*s.", "tn"),
    ("__sync_xor_and_fetch_4", "iiD*i.", "tn"),
    ("__sync_xor_and_fetch_8", "LLiLLiD*LLi.", "tn"),
    ("__sync_xor_and_fetch_16", "LLLiLLLiD*LLLi.", "tn"),
    ("__sync_nand_and_fetch", "v.", "t"),
    ("__sync_nand_and_fetch_1", "ccD*c.", "tn"),
    ("__sync_nand_and_fetch_2", "ssD*s.", "tn"),
    ("__sync_nand_and_fetch_4", "iiD*i.", "tn"),
    ("__sync_nand_and_fetch_8", "LLiLLiD*LLi.", "tn"),
    ("__sync_nand_and_fetch_16", "LLLiLLLiD*LLLi.", "tn"),
    ("__sync_bool_compare_and_swap", "v.", "t"),
    ("__sync_bool_compare_and_swap_1", "bcD*cc.", "tn"),
    ("__sync_bool_compare_and_swap_2", "bsD*ss.", "tn"),
    ("__sync_bool_compare_and_swap_4", "biD*ii.", "tn"),
    ("__sync_bool_compare_and_swap_8", "bLLiD*LLiLLi.", "tn"),
    ("__sync_bool_compare_and_swap_16", "bLLLiD*LLLiLLLi.", "tn"),
    ("__sync_val_compare_and_swap", "v.", "t"),
    ("__sync_val_compare_and_swap_1", "ccD*cc.", "tn"),
    ("__sync_val_compare_and_swap_2", "ssD*ss.", "tn"),
    ("__sync_val_compare_and_swap_4", "iiD*ii.", "tn"),
    ("__sync_val_compare_and_swap_8", "LLiLLiD*LLiLLi.", "tn"),
    ("__sync_val_compare_and_swap_16", "LLLiLLLiD*LLLiLLLi.", "tn"),
    ("__sync_lock_test_and_set", "v.", "t"),
    ("__sync_lock_test_and_set_1", "ccD*c.", "tn"),
    ("__sync_lock_test_and_set_2", "ssD*s.", "tn"),
    ("__sync_lock_test_and_set_4", "iiD*i.", "tn"),
    ("__sync_lock_test_and_set_8", "LLiLLiD*LLi.", "tn"),
    ("__sync_lock_test_and_set_16", "LLLiLLLiD*LLLi.", "tn"),
    ("__sync_lock_release", "v.", "t"),
    ("__sync_lock_release_1", "vcD*.", "tn"),
    ("__sync_lock_release_2", "vsD*.", "tn"),
    ("__sync_lock_release_4", "viD*.", "tn"),
    ("__sync_lock_release_8", "vLLiD*.", "tn"),
    ("__sync_lock_release_16", "vLLLiD*.", "tn"),
    ("__sync_swap", "v.", "t"),
    ("__sync_swap_1", "ccD*c.", "tn"),
    ("__sync_swap_2", "ssD*s.", "tn"),
    ("__sync_swap_4", "iiD*i.", "tn"),
    ("__sync_swap_8", "LLiLLiD*LLi.", "tn"),
    ("__sync_swap_16", "LLLiLLLiD*LLLi.", "tn"),
    ("__c11_atomic_init", "v.", "t"),
    ("__c11_atomic_load", "v.", "t"),
    ("__c11_atomic_store", "v.", "t"),
    ("__c11_atomic_exchange", "v.", "t"),
    ("__c11_atomic_compare_exchange_strong", "v.", "t"),
    ("__c11_atomic_compare_exchange_weak", "v.", "t"),
    ("__c11_atomic_fetch_add", "v.", "t"),
    ("__c11_atomic_fetch_sub", "v.", "t"),
    ("__c11_atomic_fetch_and", "v.", "t"),
    ("__c11_atomic_fetch_or", "v.", "t"),
    ("__c11_atomic_fetch_xor", "v.", "t"),
    ("__c11_atomic_fetch_nand", "v.", "t"),
    ("__c11_atomic_fetch_max", "v.", "t"),
    ("__c11_atomic_fetch_min", "v.", "t"),
    ("__c11_atomic_thread_fence", "vi", "n"),
    ("__c11_atomic_signal_fence", "vi", "n"),
    ("__c11_atomic_is_lock_free", "bz", "n"),
    ("__atomic_load", "v.", "t"),
    ("__atomic_load_n", "v.", "t"),
    ("__atomic_store", "v.", "t"),
    ("__atomic_store_n", "v.", "t"),
    ("__atomic_exchange", "v.", "t"),
    ("__atomic_exchange_n", "v.", "t"),
    ("__atomic_compare_exchange", "v.", "t"),
    ("__atomic_compare_exchange_n", "v.", "t"),
    ("__atomic_fetch_add", "v.", "t"),
    ("__atomic_fetch_sub", "v.", "t"),
    ("__atomic_fetch_and", "v.", "t"),
    ("__atomic_fetch_or", "v.", "t"),
    ("__atomic_fetch_xor", "v.", "t"),
    ("__atomic_fetch_nand", "v.", "t"),
    ("__atomic_add_fetch", "v.", "t"),
    ("__atomic_sub_fetch", "v.", "t"),
    ("__atomic_and_fetch", "v.", "t"),
    ("__atomic_or_fetch", "v.", "t"),
    ("__atomic_xor_fetch", "v.", "t"),
    ("__atomic_max_fetch", "v.", "t"),
    ("__atomic_min_fetch", "v.", "t"),
    ("__atomic_nand_fetch", "v.", "t"),
    ("__atomic_test_and_set", "bvD*i", "n"),
    ("__atomic_clear", "vvD*i", "n"),
    ("__atomic_thread_fence", "vi", "n"),
    ("__atomic_signal_fence", "vi", "n"),
    ("__atomic_always_lock_free", "bzvCD*", "n"),
    ("__atomic_is_lock_free", "bzvCD*", "n"),
    ("__atomic_fetch_min", "v.", "t"),
    ("__atomic_fetch_max", "v.", "t"),
    ("__hip_atomic_load", "v.", "t"),
    ("__hip_atomic_store", "v.", "t"),
    ("__hip_atomic_compare_exchange_weak", "v.", "t"),
    ("__hip_atomic_compare_exchange_strong", "v.", "t"),
    ("__hip_atomic_exchange", "v.", "t"),
    ("__hip_atomic_fetch_add", "v.", "t"),
    ("__hip_atomic_fetch_and", "v.", "t"),
    ("__hip_atomic_fetch_or", "v.", "t"),
    ("__hip_atomic_fetch_xor", "v.", "t"),
    ("__hip_atomic_fetch_min", "v.", "t"),
    ("__hip_atomic_fetch_max", "v.", "t"),
    ("__sync_synchronize", "v", "n"),
    ("__sync_fetch_and_min", "iiD*i", "n"),
    ("__sync_fetch_and_max", "iiD*i", "n"),
    ("__sync_fetch_and_umin", "UiUiD*Ui", "n"),
    ("__sync_fetch_and_umax", "UiUiD*Ui", "n"),
    ("__builtin_abort", "v", "Fnr"),
    ("__builtin_index", "c*cC*i", "Fn"),
    ("__builtin_rindex", "c*cC*i", "Fn"),
    ("__warn_memset_zero_len", "v", "nU"),
    ("__builtin_add_overflow", "b.", "nt"),
    ("__builtin_sub_overflow", "b.", "nt"),
    ("__builtin_mul_overflow", "b.", "nt"),
    ("__builtin_uadd_overflow", "bUiCUiCUi*", "n"),
    ("__builtin_uaddl_overflow", "bULiCULiCULi*", "n"),
    ("__builtin_uaddll_overflow", "bULLiCULLiCULLi*", "n"),
    ("__builtin_usub_overflow", "bUiCUiCUi*", "n"),
    ("__builtin_usubl_overflow", "bULiCULiCULi*", "n"),
    ("__builtin_usubll_overflow", "bULLiCULLiCULLi*", "n"),
    ("__builtin_umul_overflow", "bUiCUiCUi*", "n"),
    ("__builtin_umull_overflow", "bULiCULiCULi*", "n"),
    ("__builtin_umulll_overflow", "bULLiCULLiCULLi*", "n"),
    ("__builtin_sadd_overflow", "bSiCSiCSi*", "n"),
    ("__builtin_saddl_overflow", "bSLiCSLiCSLi*", "n"),
    ("__builtin_saddll_overflow", "bSLLiCSLLiCSLLi*", "n"),
    ("__builtin_ssub_overflow", "bSiCSiCSi*", "n"),
    ("__builtin_ssubl_overflow", "bSLiCSLiCSLi*", "n"),
    ("__builtin_ssubll_overflow", "bSLLiCSLLiCSLLi*", "n"),
    ("__builtin_smul_overflow", "bSiCSiCSi*", "n"),
    ("__builtin_smull_overflow", "bSLiCSLiCSLi*", "n"),
    ("__builtin_smulll_overflow", "bSLLiCSLLiCSLLi*", "n"),
    ("__builtin_addressof", "v*v&", "nct"),
    ("__builtin_function_start", "v*v&", "nct"),
    ("__builtin_operator_new", "v*z", "tc"),
    ("__builtin_operator_delete", "vv*", "tn"),
    ("__builtin_char_memchr", "c*cC*iz", "n"),
    ("__builtin_dump_struct", "ivC*v*", "tn"),
    ("__builtin_preserve_access_index", "v.", "t"),
    ("__builtin_is_aligned", "bvC*z", "nct"),
    ("__builtin_align_up", "v*vC*z", "nct"),
    ("__builtin_align_down", "v*vC*z", "nct"),
    ("__builtin___get_unsafe_stack_start", "v*", "Fn"),
    ("__builtin___get_unsafe_stack_bottom", "v*", "Fn"),
    ("__builtin___get_unsafe_stack_top", "v*", "Fn"),
    ("__builtin___get_unsafe_stack_ptr", "v*", "Fn"),
    ("__builtin_nontemporal_store", "v.", "t"),
    ("__builtin_nontemporal_load", "v.", "t"),
    ("__builtin_os_log_format_buffer_size", "zcC*.", "p:0:nut"),
    ("__builtin_os_log_format", "v*v*cC*.", "p:0:nt"),
    ("__xray_customevent", "vcC*z", ""),
    ("__xray_typedevent", "vzcC*z", ""),
    ("__builtin_ms_va_start", "vc*&.", "nt"),
    ("__builtin_ms_va_end", "vc*&", "n"),
    ("__builtin_ms_va_copy", "vc*&c*&", "n"),
    ("__builtin_annotation", "v.", "tn"),
    ("__builtin_assume", "vb", "n"),
    ("__builtin_addcb", "UcUcCUcCUcCUc*", "n"),
    ("__builtin_addcs", "UsUsCUsCUsCUs*", "n"),
    ("__builtin_addc", "UiUiCUiCUiCUi*", "n"),
    ("__builtin_addcl", "ULiULiCULiCULiCULi*", "n"),
    ("__builtin_addcll", "ULLiULLiCULLiCULLiCULLi*", "n"),
    ("__builtin_subcb", "UcUcCUcCUcCUc*", "n"),
    ("__builtin_subcs", "UsUsCUsCUsCUs*", "n"),
    ("__builtin_subc", "UiUiCUiCUiCUi*", "n"),
    ("__builtin_subcl", "ULiULiCULiCULiCULi*", "n"),
    ("__builtin_subcll", "ULLiULLiCULLiCULLiCULLi*", "n"),
)
def valid():
	if not isinstance(C_LIB_BUILTINS, dict):
		return print("expect dict", C_LIB_BUILTINS)
	for header, value_list in C_LIB_BUILTINS.items():
		if not isinstance(value_list, tuple):
			return print("expect tuple", value_list)
		for b in value_list:
			if not isinstance(b, tuple):
				return print("expect tuple", b)
			(name, attr) = b
			if not isinstance(name, str):
				return print("expect str", name, b)
			if not isinstance(attr, str):
				return print("expect str", attr, b)
	if not isinstance(COMPILER_BUILTINS, tuple):
		return print("expect tuple", COMPILER_BUILTINS)
	for b in COMPILER_BUILTINS:
		if not (
			isinstance(b, tuple) and
			(len(b) == 3) and
			isinstance(b[0], str) and
			isinstance(b[1], str) and
			isinstance(b[2], str)
			):
			return print("expect (str, str, str)", b)
	return True

assert valid(), "broken builtins table"
